/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as LifeRouteImport } from './routes/life'
import { Route as NudgesRouteImport } from './routes/nudges'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TodayRouteImport } from './routes/today'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OnboardingBirthRouteImport } from './routes/onboarding.birth'
import { Route as OnboardingConsentRouteImport } from './routes/onboarding.consent'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleIdRouteImport } from './routes/people.$id'
import { Route as PeopleNewRouteImport } from './routes/people.new'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsMemoryRouteImport } from './routes/settings.memory'
import { Route as SettingsProactiveRouteImport } from './routes/settings.proactive'
import { Route as TodayIndexRouteImport } from './routes/today.index'
import { Route as TodayHoroscopeRouteImport } from './routes/today.horoscope'
import { Route as TodayMarketsRouteImport } from './routes/today.markets'
import { Route as TodayPanchangRouteImport } from './routes/today.panchang'
import { Route as PeopleIdIndexRouteImport } from './routes/people.$id.index'
import { Route as PeopleIdCompatibilityRouteImport } from './routes/people.$id.compatibility'
import { Route as PeopleIdEditRouteImport } from './routes/people.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const LifeRoute = LifeRouteImport.update({
  id: '/life',
  path: '/life',
  getParentRoute: () => rootRouteImport,
} as any)
const NudgesRoute = NudgesRouteImport.update({
  id: '/nudges',
  path: '/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const OnboardingBirthRoute = OnboardingBirthRouteImport.update({
  id: '/onboarding/birth',
  path: '/onboarding/birth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingConsentRoute = OnboardingConsentRouteImport.update({
  id: '/onboarding/consent',
  path: '/onboarding/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleNewRoute = PeopleNewRouteImport.update({
  id: '/people/new',
  path: '/people/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsMemoryRoute = SettingsMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProactiveRoute = SettingsProactiveRouteImport.update({
  id: '/proactive',
  path: '/proactive',
  getParentRoute: () => SettingsRoute,
} as any)
const TodayIndexRoute = TodayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TodayRoute,
} as any)
const TodayHoroscopeRoute = TodayHoroscopeRouteImport.update({
  id: '/horoscope',
  path: '/horoscope',
  getParentRoute: () => TodayRoute,
} as any)
const TodayMarketsRoute = TodayMarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => TodayRoute,
} as any)
const TodayPanchangRoute = TodayPanchangRouteImport.update({
  id: '/panchang',
  path: '/panchang',
  getParentRoute: () => TodayRoute,
} as any)
const PeopleIdIndexRoute = PeopleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PeopleIdRoute,
} as any)
const PeopleIdCompatibilityRoute = PeopleIdCompatibilityRouteImport.update({
  id: '/compatibility',
  path: '/compatibility',
  getParentRoute: () => PeopleIdRoute,
} as any)
const PeopleIdEditRoute = PeopleIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PeopleIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/nudges': typeof NudgesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/today': typeof TodayRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/birth': typeof OnboardingBirthRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/people/$id': typeof PeopleIdRouteWithChildren
  '/people/new': typeof PeopleNewRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/proactive': typeof SettingsProactiveRoute
  '/today/horoscope': typeof TodayHoroscopeRoute
  '/today/markets': typeof TodayMarketsRoute
  '/today/panchang': typeof TodayPanchangRoute
  '/people/': typeof PeopleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/today/': typeof TodayIndexRoute
  '/people/$id/compatibility': typeof PeopleIdCompatibilityRoute
  '/people/$id/edit': typeof PeopleIdEditRoute
  '/people/$id/': typeof PeopleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/nudges': typeof NudgesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/birth': typeof OnboardingBirthRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/people/new': typeof PeopleNewRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/proactive': typeof SettingsProactiveRoute
  '/today/horoscope': typeof TodayHoroscopeRoute
  '/today/markets': typeof TodayMarketsRoute
  '/today/panchang': typeof TodayPanchangRoute
  '/people': typeof PeopleIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/today': typeof TodayIndexRoute
  '/people/$id/compatibility': typeof PeopleIdCompatibilityRoute
  '/people/$id/edit': typeof PeopleIdEditRoute
  '/people/$id': typeof PeopleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/home': typeof HomeRoute
  '/language': typeof LanguageRoute
  '/life': typeof LifeRoute
  '/nudges': typeof NudgesRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRouteWithChildren
  '/terms': typeof TermsRoute
  '/today': typeof TodayRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/birth': typeof OnboardingBirthRoute
  '/onboarding/consent': typeof OnboardingConsentRoute
  '/people/$id': typeof PeopleIdRouteWithChildren
  '/people/new': typeof PeopleNewRoute
  '/settings/memory': typeof SettingsMemoryRoute
  '/settings/proactive': typeof SettingsProactiveRoute
  '/today/horoscope': typeof TodayHoroscopeRoute
  '/today/markets': typeof TodayMarketsRoute
  '/today/panchang': typeof TodayPanchangRoute
  '/people/': typeof PeopleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/today/': typeof TodayIndexRoute
  '/people/$id/compatibility': typeof PeopleIdCompatibilityRoute
  '/people/$id/edit': typeof PeopleIdEditRoute
  '/people/$id/': typeof PeopleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/home'
    | '/language'
    | '/life'
    | '/nudges'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/today'
    | '/auth/callback'
    | '/onboarding/birth'
    | '/onboarding/consent'
    | '/people/$id'
    | '/people/new'
    | '/settings/memory'
    | '/settings/proactive'
    | '/today/horoscope'
    | '/today/markets'
    | '/today/panchang'
    | '/people/'
    | '/settings/'
    | '/today/'
    | '/people/$id/compatibility'
    | '/people/$id/edit'
    | '/people/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/home'
    | '/language'
    | '/life'
    | '/nudges'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/auth/callback'
    | '/onboarding/birth'
    | '/onboarding/consent'
    | '/people/new'
    | '/settings/memory'
    | '/settings/proactive'
    | '/today/horoscope'
    | '/today/markets'
    | '/today/panchang'
    | '/people'
    | '/settings'
    | '/today'
    | '/people/$id/compatibility'
    | '/people/$id/edit'
    | '/people/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/home'
    | '/language'
    | '/life'
    | '/nudges'
    | '/privacy'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/today'
    | '/auth/callback'
    | '/onboarding/birth'
    | '/onboarding/consent'
    | '/people/$id'
    | '/people/new'
    | '/settings/memory'
    | '/settings/proactive'
    | '/today/horoscope'
    | '/today/markets'
    | '/today/panchang'
    | '/people/'
    | '/settings/'
    | '/today/'
    | '/people/$id/compatibility'
    | '/people/$id/edit'
    | '/people/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  HomeRoute: typeof HomeRoute
  LanguageRoute: typeof LanguageRoute
  LifeRoute: typeof LifeRoute
  NudgesRoute: typeof NudgesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TermsRoute: typeof TermsRoute
  TodayRoute: typeof TodayRouteWithChildren
  OnboardingBirthRoute: typeof OnboardingBirthRoute
  OnboardingConsentRoute: typeof OnboardingConsentRoute
  PeopleIdRoute: typeof PeopleIdRouteWithChildren
  PeopleNewRoute: typeof PeopleNewRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/life': {
      id: '/life'
      path: '/life'
      fullPath: '/life'
      preLoaderRoute: typeof LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nudges': {
      id: '/nudges'
      path: '/nudges'
      fullPath: '/nudges'
      preLoaderRoute: typeof NudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/onboarding/birth': {
      id: '/onboarding/birth'
      path: '/onboarding/birth'
      fullPath: '/onboarding/birth'
      preLoaderRoute: typeof OnboardingBirthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/consent': {
      id: '/onboarding/consent'
      path: '/onboarding/consent'
      fullPath: '/onboarding/consent'
      preLoaderRoute: typeof OnboardingConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/new': {
      id: '/people/new'
      path: '/people/new'
      fullPath: '/people/new'
      preLoaderRoute: typeof PeopleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/memory': {
      id: '/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SettingsMemoryRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/proactive': {
      id: '/settings/proactive'
      path: '/proactive'
      fullPath: '/settings/proactive'
      preLoaderRoute: typeof SettingsProactiveRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/today/': {
      id: '/today/'
      path: '/'
      fullPath: '/today/'
      preLoaderRoute: typeof TodayIndexRouteImport
      parentRoute: typeof TodayRoute
    }
    '/today/horoscope': {
      id: '/today/horoscope'
      path: '/horoscope'
      fullPath: '/today/horoscope'
      preLoaderRoute: typeof TodayHoroscopeRouteImport
      parentRoute: typeof TodayRoute
    }
    '/today/markets': {
      id: '/today/markets'
      path: '/markets'
      fullPath: '/today/markets'
      preLoaderRoute: typeof TodayMarketsRouteImport
      parentRoute: typeof TodayRoute
    }
    '/today/panchang': {
      id: '/today/panchang'
      path: '/panchang'
      fullPath: '/today/panchang'
      preLoaderRoute: typeof TodayPanchangRouteImport
      parentRoute: typeof TodayRoute
    }
    '/people/$id/': {
      id: '/people/$id/'
      path: '/'
      fullPath: '/people/$id/'
      preLoaderRoute: typeof PeopleIdIndexRouteImport
      parentRoute: typeof PeopleIdRoute
    }
    '/people/$id/compatibility': {
      id: '/people/$id/compatibility'
      path: '/compatibility'
      fullPath: '/people/$id/compatibility'
      preLoaderRoute: typeof PeopleIdCompatibilityRouteImport
      parentRoute: typeof PeopleIdRoute
    }
    '/people/$id/edit': {
      id: '/people/$id/edit'
      path: '/edit'
      fullPath: '/people/$id/edit'
      preLoaderRoute: typeof PeopleIdEditRouteImport
      parentRoute: typeof PeopleIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SettingsRouteChildren {
  SettingsMemoryRoute: typeof SettingsMemoryRoute
  SettingsProactiveRoute: typeof SettingsProactiveRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsMemoryRoute: SettingsMemoryRoute,
  SettingsProactiveRoute: SettingsProactiveRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TodayRouteChildren {
  TodayHoroscopeRoute: typeof TodayHoroscopeRoute
  TodayMarketsRoute: typeof TodayMarketsRoute
  TodayPanchangRoute: typeof TodayPanchangRoute
  TodayIndexRoute: typeof TodayIndexRoute
}

const TodayRouteChildren: TodayRouteChildren = {
  TodayHoroscopeRoute: TodayHoroscopeRoute,
  TodayMarketsRoute: TodayMarketsRoute,
  TodayPanchangRoute: TodayPanchangRoute,
  TodayIndexRoute: TodayIndexRoute,
}

const TodayRouteWithChildren = TodayRoute._addFileChildren(TodayRouteChildren)

interface PeopleIdRouteChildren {
  PeopleIdCompatibilityRoute: typeof PeopleIdCompatibilityRoute
  PeopleIdEditRoute: typeof PeopleIdEditRoute
  PeopleIdIndexRoute: typeof PeopleIdIndexRoute
}

const PeopleIdRouteChildren: PeopleIdRouteChildren = {
  PeopleIdCompatibilityRoute: PeopleIdCompatibilityRoute,
  PeopleIdEditRoute: PeopleIdEditRoute,
  PeopleIdIndexRoute: PeopleIdIndexRoute,
}

const PeopleIdRouteWithChildren = PeopleIdRoute._addFileChildren(
  PeopleIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  HomeRoute: HomeRoute,
  LanguageRoute: LanguageRoute,
  LifeRoute: LifeRoute,
  NudgesRoute: NudgesRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TermsRoute: TermsRoute,
  TodayRoute: TodayRouteWithChildren,
  OnboardingBirthRoute: OnboardingBirthRoute,
  OnboardingConsentRoute: OnboardingConsentRoute,
  PeopleIdRoute: PeopleIdRouteWithChildren,
  PeopleNewRoute: PeopleNewRoute,
  PeopleIndexRoute: PeopleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
